AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a simple VPC

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

Outputs:
  VpcId:
    Value: !Ref MyVPC
    Description: The ID of the VPC
